// Mirror note: RESULT.md is the monorepo's build log for this server and is not
// published to a mirror, so it is dropped from the required-file list below. Every
// other file in that list is still checked.
// Mirror note: tests that need a signed Pro key are skipped here. The signing key
// lives only in the monorepo (keys/license-private.pem); run them there.
// Mirror note: a test that reads monorepo files through a table of paths is skipped
// here. Those files live outside any server folder and never reach a mirror; run it
// in the monorepo, which is the only place it can mean anything.
// Mirror note: tests that run a script from the monorepo's scripts/ directory are
// skipped here. That directory is not part of a server folder; run them in the monorepo.
// Contract suite for service-agreement. Mechanical assertions only.
//
// Asserts the invariants of servers/service-agreement/SPEC.md that a test can check
// without judgement: one version number across package.json, src/version.ts, serverInfo
// and all three registry manifests; the remotes rule (the mcpb manifest carries
// remotes.json, the stdio-only name carries none); JSON-RPC-only stdout;
// tool-description hygiene; the free/Pro tier switch; that nothing outside this server's
// own two files is written; and that the status machine moves one step at a time. It
// never asserts a number a human chose; those live in test/smoke.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, AGREEMENT, REPO } from "./_client.mjs";

const HERE = REPO;
const PRODUCT = "service-agreement";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const MANIFESTS = ["server.json", "server.mcpb.json", "server.variant.json"];

/**
 * Tools that already break the description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. The fix is in
 * src, not here.
 */
const OVER_LENGTH_BASELINE = ["agreement_checklist", "agreement_create", "agreement_get", "agreement_render", "agreement_update_status", "clause_library"];

function open(t, opts = {}) {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test.skip("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-service-agreement");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-service-agreement");

  for (const file of MANIFESTS) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until scripts/manifest-sha256.mjs hashes the built bundle; after that, the
        // real digest. A STALE digest is worse than none.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/service-agreement)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/service-agreement");
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
    assert.ok(!/\u2014/.test(JSON.stringify(j)), `${file} carries an em dash`);
  }
  assert.ok(existsSync(join(HERE, "remotes.json")), "remotes.json is missing: this server has a hosted route in remote/src/index.ts");

  // server.json and server.mcpb.json share the primary name; the variant is the second listing.
  const names = MANIFESTS.map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 2, `registry names must be one primary and one variant: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/service-agreement",
    "io.github.theluckystrike/service-agreement",
    "io.github.theluckystrike/service-contract",
  ]);

  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("every registry name carries a token this server can actually be found on", () => {
  // Registry search matches a substring of the FULL name and nothing else; the description
  // is never searched. So the tokens this server is meant to be findable on have to be IN
  // the names, and this asserts they are rather than assuming it.
  const joined = MANIFESTS.map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name.toLowerCase()).join(" ");
  for (const token of ["service", "agreement", "contract"]) {
    assert.ok(joined.includes(token), `no registry name carries the token "${token}"`);
  }
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("agreement_create", AGREEMENT);
  await c.call("agreement_get", { agreement: "SA-2099-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = c.stdoutLines.filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 9, "tool count changed; update servers/service-agreement/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "agreement_checklist", "agreement_create", "agreement_get", "agreement_list",
    "agreement_render", "agreement_update_status", "clause_library",
    "license_activate", "license_status",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/\u2014/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  assert.deepEqual(over.filter((n) => !OVER_LENGTH_BASELINE.includes(n)), [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("no tool takes a file path, so nothing here writes outside its own data directory", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const FILE_ARGS = ["path", "url", "out_path", "template_path"];
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), [], "a file-path argument appeared; agreement_render returns text and writes nothing");
});

test.skip("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test.skip("a licence for another product does not unlock this one", async (t) => {
  const { c } = open(t, { key: proKey("not-a-real-product") });
  await c.init();
  assert.match((await c.call("license_status", {})).text, /"tier":\s*"free"/);
});

test("the free tier is the documented one: everything but the fourth active agreement, the clause texts and HTML", async (t) => {
  const { c } = open(t);
  await c.init();
  const j = await c.json("agreement_create", AGREEMENT);
  const id = j.created.id;
  for (const [tool, args] of [
    ["agreement_get", { agreement: id }],
    ["agreement_list", {}],
    ["agreement_update_status", { agreement: id, status: "sent", date: "2026-10-01" }],
    ["agreement_render", { agreement: id }],
    ["agreement_checklist", { agreement: id }],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, false, `${tool} was gated: ${r.text}`);
  }
  const html = await c.call("agreement_render", { agreement: id, format: "html" });
  assert.ok(html.isError, "HTML rendering is Pro and answered free");
  const lib = await c.json("clause_library", {});
  assert.equal(lib.pro, false, "the free clause library must say so");
  assert.ok(lib.clauses.every((x) => x.body === undefined), "the free tier returned clause bodies");
});

test("library clauses on an agreement are a Pro feature, refused before anything is written", async (t) => {
  const { box, c } = open(t);
  await c.init();
  const r = await c.call("agreement_create", { ...AGREEMENT, clauses: ["ip_assignment"] });
  assert.ok(r.isError, r.text);
  assert.match(r.text, /Pro is a one-time \$\d+ for this server/);
  assert.match(r.text, /license_activate/);
  assert.match(r.text, new RegExp(`src=${PRODUCT}\\.agreement_create`), "the gate link is untagged");
  assert.match(r.text, /buy\/bundle/);
  assert.equal(existsSync(join(storeDir(box.dataHome), "agreements.json")), false, "the refused agreement was written");
});

test("the free-tier active-agreement cap carries the tagged link, and expiring frees the slot", async (t) => {
  const { box, c } = open(t);
  await c.init();
  const ids = [];
  for (let i = 1; i <= 3; i++) ids.push((await c.json("agreement_create", { ...AGREEMENT, client: `Client ${i}` })).created.id);
  const r = await c.call("agreement_create", { ...AGREEMENT, client: "Client 4" });
  assert.ok(r.isError, r.text);
  assert.match(r.text, /3 active agreements/);
  assert.match(r.text, /Pro is a one-time \$\d+ for this server/);
  assert.match(r.text, new RegExp(`src=${PRODUCT}\\.agreement_create`), "the gate link is untagged");
  assert.match(r.text, /buy\/bundle/);
  const stored = JSON.parse(readFileSync(join(storeDir(box.dataHome), "agreements.json"), "utf8"));
  assert.equal(stored.length, 3, "the refused fourth agreement was written");
  for (const status of ["sent", "signed", "expired"]) {
    assert.equal((await c.call("agreement_update_status", { agreement: ids[0], status, date: "2026-10-01" })).isError, false, status);
  }
  const again = await c.call("agreement_create", { ...AGREEMENT, client: "Client 4" });
  assert.equal(again.isError, false, `expiring did not free the slot: ${again.text}`);
});

test("the status machine moves one step at a time and a skipped step is refused", async (t) => {
  const { c } = open(t);
  await c.init();
  const j = await c.json("agreement_create", AGREEMENT);
  const id = j.created.id;
  const skip = await c.call("agreement_update_status", { agreement: id, status: "signed", date: "2026-10-01" });
  assert.ok(skip.isError, "draft jumped straight to signed");
  assert.match(skip.text, /one step at a time/);
  const same = await c.call("agreement_update_status", { agreement: id, status: "draft", date: "2026-10-01" });
  assert.ok(same.isError, "re-stamping the current status was allowed");
});

test("an end date before the start date and an unknown clause id are both refused", async (t) => {
  const { c } = open(t);
  await c.init();
  const dates = await c.call("agreement_create", { ...AGREEMENT, start_date: "2026-12-31", end_date: "2026-10-01" });
  assert.ok(dates.isError, "an end before the start was stored");
  assert.match(dates.text, /before the start/);
  const clause = await c.call("agreement_create", { ...AGREEMENT, clauses: ["no-such-clause"] });
  assert.ok(clause.isError, "an unknown clause id was accepted");
  assert.match(clause.text, /not a clause in the library/);
});

test("there are no resources and no prompts on this server: both methods answer Method not found", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = await c.send("resources/list", {});
  const pr = await c.send("prompts/list", {});
  for (const r of [res, pr]) {
    // No capability is registered, so the SDK answers Method not found rather than an empty list.
    assert.equal(r.error?.code, -32601, JSON.stringify(r).slice(0, 200));
  }
});

test.skip("this server writes two files and no others, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const j = await c.json("agreement_create", AGREEMENT);
  await c.call("agreement_update_status", { agreement: j.created.id, status: "sent", date: "2026-10-01" });
  await c.call("agreement_list", {});
  await c.call("agreement_get", { agreement: j.created.id });
  await c.call("agreement_checklist", { agreement: j.created.id });
  await c.call("agreement_render", { agreement: j.created.id });
  await c.call("agreement_render", { agreement: j.created.id, format: "html" });
  await c.call("clause_library", { agreement: j.created.id });

  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["agreements.json", "counter.json"]);
  const siblings = readdirSync(join(box.dataHome, "mcp-servers"));
  assert.deepEqual(siblings, ["service-agreement"], `a sibling store was touched: ${siblings.join(", ")}`);
});

test("src holds no network call and no stdout write", async () => {
  let raw = "";
  try {
    raw = execFileSync("/usr/bin/grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const offending = raw.trim().split("\n").filter(Boolean)
    .filter((l) => !/mcp\.zovo\.one|github\.com|modelcontextprotocol\.io/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("src, tests and docs carry no em dash and no emoji", () => {
  const files = [
    ...readdirSync(join(HERE, "src")).map((f) => join(HERE, "src", f)),
    ...readdirSync(join(HERE, "test")).map((f) => join(HERE, "test", f)),
    join(HERE, "README.md"), join(HERE, "llms-install.md"), join(HERE, "RESULT.md"), join(HERE, "SPEC.md"),
  ].filter(existsSync);
  for (const f of files) {
    const s = readFileSync(f, "utf8");
    assert.equal(s.includes("\u2014"), false, `${f} carries an em dash`);
    assert.equal(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(s), false, `${f} carries an emoji`);
  }
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md",
    "server.json", "server.mcpb.json", "server.variant.json",
    "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/agreement.ts", "src/store.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test.skip("the estate lists this server everywhere a new server has to be registered", () => {
  // The one-line registrations outside this folder. release-check.mjs is the full reader;
  // these are the ones a server cannot ship without, checked here so the omission fails in
  // this suite rather than at bundle time. This server reads no shared profile, so
  // PROFILE_READERS correctly does NOT list it and there is no positive case to assert here.
  const cases = [
    ["scripts/build-mcpb.sh", /^SERVERS="[^"]*\bservice-agreement\b/m, "SERVERS list"],
    ["scripts/build-mcpb.sh", /^\s*\[service-agreement\]="/m, "DISPLAY_NAME"],
    ["scripts/build-mcpb.sh", /^\s*\[service-agreement\]='\[/m, "KEYWORDS"],
    ["scripts/build-pages.mjs", /const ids = \[[^\]]*"service-agreement"/, "page ids"],
    ["scripts/gen-spec.mjs", /"service-agreement"/, "SPEC generator"],
    ["servers/office-suite/src/index.ts", /id: "service-agreement"/, "office-suite CHILDREN"],
    ["data/facts.json", /"service-agreement":/, "facts tagline, which the README table is generated from"],
    ["data/distribution.json", /"service-agreement":/, "distribution per_server"],
    ["data/tools.json", /"service-agreement":/, "tools.json, which the storefront tool tables read"],
    ["scripts/sync-mirrors.sh", /^ALL_SERVERS="[^"]*\bservice-agreement\b/m, "ALL_SERVERS"],
    ["scripts/mirror-seo.py", /^\s*"service-agreement":/m, "mirror-seo CAPABILITY and topics"],
  ];
  for (const [file, re, what] of cases) {
    const src = readFileSync(join(REPO, file), "utf8");
    assert.ok(re.test(src), `${file} does not list service-agreement in its ${what}`);
  }
});

test.skip("the hosted registration is exactly one of two honest states", () => {
  // The hosted route for this server exists in remote/src/index.ts and the worker deploy is
  // pending (docs/HOSTED_LOOP35.md deploys; wave C wires). data/distribution.json must say
  // one of two things and nothing in between: the ONLY string that means live is the exact
  // published URL, because scripts/kpi.mjs counts hosted servers by string match.
  const dist = JSON.parse(readFileSync(join(REPO, "data", "distribution.json"), "utf8"));
  const hosted = String(dist.per_server["service-agreement"].hosted);
  const published = "published https://mcp.zovo.one/mcp/service-agreement";
  assert.ok(hosted === published || hosted.startsWith("none by design") || hosted.startsWith("pending deploy:"),
    `distribution.json per_server.service-agreement.hosted is neither the exact published string nor a pending note: ${hosted}`);
  // And the live-validation remote sweep covers this server, added by the wiring loop.
  const validate = readFileSync(join(REPO, "scripts", "validate.mjs"), "utf8");
  const remoteBlock = validate.slice(validate.indexOf("async function remote()"));
  assert.ok(remoteBlock.includes('"service-agreement"'), "scripts/validate.mjs remote() does not probe service-agreement");
});
